"""Idempotent Google Cloud discovery + setup for Walk-In Wardrobe.

    python infra/gcp.py status   # found / missing table, what we created, rough monthly cost
    python infra/gcp.py setup    # create only what is missing (all names prefixed wiw-)

Rules: never delete or modify resources we did not create. Everything we create is recorded in
infra/created_resources.json and rendered to infra/created_resources.md with a stop/delete command.
Uses the gcloud CLI's user credentials (no ADC needed).
"""
from __future__ import annotations

import json
import secrets
import subprocess
import sys
import time
from datetime import date
from pathlib import Path

import requests
import yaml

ROOT = Path(__file__).resolve().parents[1]
CFG = yaml.safe_load((ROOT / "config/cloud.yaml").read_text())
P = CFG["project"]
REGION = CFG["region"]
STATE = ROOT / "infra/created_resources.json"
DOC = ROOT / "infra/created_resources.md"
SA_EMAIL = f"{CFG['service_account']}@{P}.iam.gserviceaccount.com"
APIS = [
    "aiplatform.googleapis.com", "discoveryengine.googleapis.com", "run.googleapis.com",
    "artifactregistry.googleapis.com", "cloudbuild.googleapis.com", "storage.googleapis.com",
    "bigquery.googleapis.com", "sqladmin.googleapis.com", "secretmanager.googleapis.com",
    "billingbudgets.googleapis.com",
]
SA_PROJECT_ROLES = [
    "roles/aiplatform.user", "roles/discoveryengine.viewer", "roles/bigquery.jobUser",
    "roles/cloudsql.client", "roles/logging.logWriter",
]


def sh(cmd: str, check: bool = False) -> tuple[int, str]:
    r = subprocess.run(cmd, shell=True, capture_output=True, text=True)
    out = (r.stdout + r.stderr).strip()
    if check and r.returncode != 0:
        raise SystemExit(f"FAILED: {cmd}\n{out}")
    return r.returncode, out


def token() -> str:
    return sh("gcloud auth print-access-token", check=True)[1].splitlines()[-1]


def de(method: str, path: str, body: dict | None = None) -> requests.Response:
    loc = CFG["search"]["location"]
    host = "discoveryengine.googleapis.com" if loc == "global" else f"{loc}-discoveryengine.googleapis.com"
    url = f"https://{host}/v1/projects/{P}/locations/{loc}/collections/default_collection/{path}"
    return requests.request(method, url, json=body, timeout=60, headers={
        "Authorization": f"Bearer {token()}", "x-goog-user-project": P})


# ---------------------------------------------------------------- state / doc

def load_state() -> dict:
    return json.loads(STATE.read_text()) if STATE.exists() else {"created": []}


def record(kind: str, name: str, stop: str, cost: str, note: str = "") -> None:
    st = load_state()
    if not any(c["kind"] == kind and c["name"] == name for c in st["created"]):
        st["created"].append({"kind": kind, "name": name, "stop": stop, "cost": cost,
                              "note": note, "created": date.today().isoformat()})
        STATE.write_text(json.dumps(st, indent=2) + "\n")
    render_doc()


def render_doc() -> None:
    st = load_state()
    lines = [
        "# Google Cloud resources created by Walk-In Wardrobe", "",
        f"Project: `{P}` (reused, not created by us). Region: `{REGION}`.", "",
        "This file is generated by `infra/gcp.py` from `created_resources.json`. Each row is something",
        "**we created**; reused resources (the project, the `atelieros-pg` Cloud SQL instance, existing APIs)",
        "are listed at the bottom and must not be deleted from here.", "",
        "| Kind | Name | Created | Rough monthly cost | Stop / delete |",
        "|---|---|---|---|---|",
    ]
    for c in st["created"]:
        note = f" ({c['note']})" if c.get("note") else ""
        lines.append(f"| {c['kind']} | `{c['name']}`{note} | {c['created']} | {c['cost']} | `{c['stop']}` |")
    lines += [
        "", "## Reused (not ours, do not delete)", "",
        f"- Project `{P}` and its billing link.",
        f"- Cloud SQL instance `{CFG['cloudsql']['instance']}`: we only added database "
        f"`{CFG['cloudsql']['database']}` and user `{CFG['cloudsql']['user']}` (listed above).",
        "- APIs that were already enabled.", "",
        "## Stop everything quickly", "",
        "Cloud Run scales to zero on its own (min instances 0). To stop all spend from this project's",
        "resources, run the commands in the table from the bottom up.",
    ]
    DOC.write_text("\n".join(lines) + "\n")


# ---------------------------------------------------------------- discovery

def discover() -> dict[str, bool | str]:
    found: dict[str, bool | str] = {}
    _, billing = sh(f"gcloud billing projects describe {P} --format='value(billingEnabled)'")
    found["billing linked"] = billing.strip() == "True"
    _, apis = sh(f"gcloud services list --enabled --project {P} --format='value(config.name)'")
    for a in APIS:
        found[f"api {a.split('.')[0]}"] = a in apis.split()
    _, b = sh(f"gcloud storage buckets describe gs://{CFG['bucket']} --format='value(name)'")
    found[f"bucket {CFG['bucket']}"] = CFG["bucket"] in b and "ERROR" not in b
    rc, _ = sh(f"bq --project_id={P} show --format=none {P}:{CFG['bq_dataset']}")
    found[f"bq dataset {CFG['bq_dataset']}"] = rc == 0
    sql = CFG["cloudsql"]
    _, inst = sh(f"gcloud sql instances describe {sql['instance']} --project {P} --format='value(state)'")
    found[f"cloudsql instance {sql['instance']} (reuse)"] = inst.strip() == "RUNNABLE"
    _, dbs = sh(f"gcloud sql databases list -i {sql['instance']} --project {P} --format='value(name)'")
    found[f"cloudsql database {sql['database']}"] = sql["database"] in dbs.split()
    _, users = sh(f"gcloud sql users list -i {sql['instance']} --project {P} --format='value(name)'")
    found[f"cloudsql user {sql['user']}"] = sql["user"] in users.split()
    rc, _ = sh(f"gcloud secrets describe {sql['password_secret']} --project {P}")
    found[f"secret {sql['password_secret']}"] = rc == 0
    rc, _ = sh(f"gcloud artifacts repositories describe {CFG['artifact_repo']} --location {REGION} --project {P}")
    found[f"artifact repo {CFG['artifact_repo']}"] = rc == 0
    rc, _ = sh(f"gcloud iam service-accounts describe {SA_EMAIL} --project {P}")
    found[f"service account {CFG['service_account']}"] = rc == 0
    s = CFG["search"]
    found[f"search datastore {s['datastore']}"] = de("GET", f"dataStores/{s['datastore']}").status_code == 200
    found[f"search engine {s['engine']}"] = de("GET", f"engines/{s['engine']}").status_code == 200
    _, run = sh(f"gcloud run services describe {CFG['run_service']} --region {REGION} --project {P} --format='value(status.url)'")
    found[f"cloud run {CFG['run_service']}"] = run if run.startswith("https://") else False
    _, bud = sh(f"gcloud billing budgets list --billing-account={billing_account()} --billing-project={P} --format='value(displayName)'")
    found[f"budget {CFG['budget']['name']}"] = CFG["budget"]["name"] in bud.splitlines()
    return found


def billing_account() -> str:
    _, out = sh(f"gcloud billing projects describe {P} --format='value(billingAccountName)'")
    return out.strip().split("/")[-1]


def print_table(found: dict) -> None:
    w = max(len(k) for k in found)
    print(f"\n{'resource'.ljust(w)}  status")
    print(f"{'-' * w}  ------")
    for k, v in found.items():
        status = "found" if v else "MISSING"
        if isinstance(v, str) and v:
            status = f"found  {v}"
        print(f"{k.ljust(w)}  {status}")


def status() -> None:
    print(f"project {P}  region {REGION}  gemini {CFG['gemini']['model']}@{CFG['gemini']['location']}")
    print_table(discover())
    st = load_state()
    print(f"\nCreated by this project ({len(st['created'])}):")
    for c in st["created"]:
        print(f"  - {c['kind']:<22} {c['name']:<40} {c['cost']}")
    print("\nRough monthly cost of what we added (idle demo usage):")
    print("  Cloud Run (min 0)            ~ ₹0-100    pay per request")
    print("  Vertex AI Search (standard)  ~ ₹100-400  ~90 docs; queries billed per 1k")
    print("  Gemini on Vertex AI          ~ ₹50-300   cached; replay mode makes no calls")
    print("  BigQuery / GCS / AR / Secret ~ ₹0-100    tiny volumes, mostly free tier")
    print("  Cloud SQL                    ₹0 extra    reused instance, new database only")
    print("  Total                        ~ ₹150-900 / month   (budget alert at ₹%d)" % CFG["budget"]["amount_inr"])


# ---------------------------------------------------------------- setup

def wait_op(op: dict) -> None:
    name = op.get("name")
    for _ in range(60):
        if op.get("done"):
            if "error" in op:
                raise SystemExit(f"operation failed: {op['error']}")
            return
        time.sleep(5)
        loc = CFG["search"]["location"]
        host = "discoveryengine.googleapis.com" if loc == "global" else f"{loc}-discoveryengine.googleapis.com"
        op = requests.get(f"https://{host}/v1/{name}", timeout=30, headers={
            "Authorization": f"Bearer {token()}", "x-goog-user-project": P}).json()


def setup() -> None:
    found = discover()
    print("Before setup:")
    print_table(found)
    if not found["billing linked"]:
        raise SystemExit("Billing is not linked to the project. Link a billing account and re-run.")

    missing_apis = [a for a in APIS if not found[f"api {a.split('.')[0]}"]]
    if missing_apis:
        sh(f"gcloud services enable {' '.join(missing_apis)} --project {P}", check=True)
        for a in missing_apis:
            record("api", a, f"gcloud services disable {a} --project {P}", "₹0")

    if not found[f"bucket {CFG['bucket']}"]:
        sh(f"gcloud storage buckets create gs://{CFG['bucket']} --project {P} --location {REGION} "
           f"--uniform-bucket-level-access --public-access-prevention", check=True)
        record("storage bucket", CFG["bucket"], f"gcloud storage rm -r gs://{CFG['bucket']}", "< ₹10")

    if not found[f"bq dataset {CFG['bq_dataset']}"]:
        sh(f"bq --project_id={P} --location={CFG['bq_location']} mk --dataset "
           f"--description 'Walk-In Wardrobe events' {P}:{CFG['bq_dataset']}", check=True)
        record("bigquery dataset", CFG["bq_dataset"], f"bq rm -r -f {P}:{CFG['bq_dataset']}", "< ₹10")

    sql = CFG["cloudsql"]
    if not found[f"cloudsql instance {sql['instance']} (reuse)"]:
        raise SystemExit(f"Expected to reuse Cloud SQL instance {sql['instance']} but it is not RUNNABLE.")
    if not found[f"cloudsql database {sql['database']}"]:
        sh(f"gcloud sql databases create {sql['database']} -i {sql['instance']} --project {P}", check=True)
        record("cloudsql database", f"{sql['instance']}/{sql['database']}",
               f"gcloud sql databases delete {sql['database']} -i {sql['instance']} --project {P}", "₹0 (reused instance)")
    if not found[f"secret {sql['password_secret']}"]:
        pw = secrets.token_urlsafe(24)
        sh(f"printf %s '{pw}' | gcloud secrets create {sql['password_secret']} --project {P} "
           f"--replication-policy=automatic --data-file=-", check=True)
        record("secret", sql["password_secret"], f"gcloud secrets delete {sql['password_secret']} --project {P}", "< ₹10")
    if not found[f"cloudsql user {sql['user']}"]:
        _, pw = sh(f"gcloud secrets versions access latest --secret {sql['password_secret']} --project {P}", check=True)
        sh(f"gcloud sql users create {sql['user']} -i {sql['instance']} --project {P} --password='{pw.strip()}'", check=True)
        record("cloudsql user", f"{sql['instance']}/{sql['user']}",
               f"gcloud sql users delete {sql['user']} -i {sql['instance']} --project {P}", "₹0")

    if not found[f"artifact repo {CFG['artifact_repo']}"]:
        sh(f"gcloud artifacts repositories create {CFG['artifact_repo']} --repository-format=docker "
           f"--location {REGION} --project {P} --description 'Walk-In Wardrobe images'", check=True)
        record("artifact registry repo", CFG["artifact_repo"],
               f"gcloud artifacts repositories delete {CFG['artifact_repo']} --location {REGION} --project {P}", "< ₹20")

    if not found[f"service account {CFG['service_account']}"]:
        sh(f"gcloud iam service-accounts create {CFG['service_account']} --project {P} "
           f"--display-name 'Walk-In Wardrobe Cloud Run'", check=True)
        record("service account", SA_EMAIL, f"gcloud iam service-accounts delete {SA_EMAIL} --project {P}", "₹0")
        time.sleep(10)
    grant_roles()

    s = CFG["search"]
    if not found[f"search datastore {s['datastore']}"]:
        r = de("POST", f"dataStores?dataStoreId={s['datastore']}", {
            "displayName": "wiw catalog", "industryVertical": "GENERIC",
            "solutionTypes": ["SOLUTION_TYPE_SEARCH"], "contentConfig": "NO_CONTENT"})
        if r.status_code >= 300:
            raise SystemExit(f"datastore create failed: {r.text}")
        wait_op(r.json())
        record("vertex ai search datastore", s["datastore"],
               f"curl -X DELETE -H \"Authorization: Bearer $(gcloud auth print-access-token)\" "
               f"https://discoveryengine.googleapis.com/v1/projects/{P}/locations/{s['location']}/collections/default_collection/dataStores/{s['datastore']}",
               "~ ₹50 (index storage)")
    if not found[f"search engine {s['engine']}"]:
        r = de("POST", f"engines?engineId={s['engine']}", {
            "displayName": "wiw search", "solutionType": "SOLUTION_TYPE_SEARCH",
            "industryVertical": "GENERIC", "dataStoreIds": [s["datastore"]],
            "searchEngineConfig": {"searchTier": "SEARCH_TIER_STANDARD"}})
        if r.status_code >= 300:
            raise SystemExit(f"engine create failed: {r.text}")
        wait_op(r.json())
        record("vertex ai search app", s["engine"],
               f"curl -X DELETE -H \"Authorization: Bearer $(gcloud auth print-access-token)\" "
               f"https://discoveryengine.googleapis.com/v1/projects/{P}/locations/{s['location']}/collections/default_collection/engines/{s['engine']}",
               "~ ₹50-300 (per 1k queries)")

    if not found[f"budget {CFG['budget']['name']}"]:
        ba = billing_account()
        sh(f"gcloud billing budgets create --billing-account={ba} --billing-project={P} "
           f"--display-name={CFG['budget']['name']} --budget-amount={CFG['budget']['amount_inr']}INR "
           f"--filter-projects=projects/{P} --threshold-rule=percent=0.5 "
           f"--threshold-rule=percent=0.9 --threshold-rule=percent=1.0", check=True)
        record("billing budget", CFG["budget"]["name"],
               f"gcloud billing budgets list --billing-account={ba} (then: gcloud billing budgets delete <ID> --billing-account={ba})",
               "₹0", note=f"alerts at 50/90/100% of ₹{CFG['budget']['amount_inr']}")

    render_doc()
    print("\nAfter setup:")
    print_table(discover())


def grant_roles() -> None:
    member = f"serviceAccount:{SA_EMAIL}"
    for role in SA_PROJECT_ROLES:
        sh(f"gcloud projects add-iam-policy-binding {P} --member={member} --role={role} "
           f"--condition=None --quiet --format=none", check=True)
    sh(f"gcloud storage buckets add-iam-policy-binding gs://{CFG['bucket']} --member={member} "
       f"--role=roles/storage.objectAdmin --format=none", check=True)
    sh(f"gcloud secrets add-iam-policy-binding {CFG['cloudsql']['password_secret']} --project {P} "
       f"--member={member} --role=roles/secretmanager.secretAccessor --format=none", check=True)
    # Dataset-level BigQuery write access (not project-wide).
    ds = f"{P}:{CFG['bq_dataset']}"
    _, raw = sh(f"bq --project_id={P} show --format=prettyjson {ds}", check=True)
    meta = json.loads(raw)
    access = meta.get("access", [])
    if not any(a.get("userByEmail") == SA_EMAIL for a in access):
        access.append({"role": "WRITER", "userByEmail": SA_EMAIL})
        tmp = ROOT / "infra/.ds_access.json"
        tmp.write_text(json.dumps({"access": access}))
        sh(f"bq --project_id={P} update --source {tmp} {ds}", check=True)
        tmp.unlink()
    record("iam bindings", SA_EMAIL,
           f"gcloud projects remove-iam-policy-binding {P} --member={member} --role=<role> (for each role)",
           "₹0", note="project: " + ", ".join(r.split('/')[1] for r in SA_PROJECT_ROLES)
           + "; bucket objectAdmin; secret accessor; dataset WRITER")


if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else "status"
    {"status": status, "setup": setup}[cmd]()
