/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BoardRouteImport } from './routes/board'
import { Route as CartRouteImport } from './routes/cart'
import { Route as InspoRouteImport } from './routes/inspo'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PreferencesRouteImport } from './routes/preferences'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as TasteRouteImport } from './routes/taste'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as FoldersIdRouteImport } from './routes/folders.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const InspoRoute = InspoRouteImport.update({
  id: '/inspo',
  path: '/inspo',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PreferencesRoute = PreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const TasteRoute = TasteRouteImport.update({
  id: '/taste',
  path: '/taste',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const FoldersIdRoute = FoldersIdRouteImport.update({
  id: '/folders/$id',
  path: '/folders/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/board': typeof BoardRoute
  '/cart': typeof CartRoute
  '/inspo': typeof InspoRoute
  '/notifications': typeof NotificationsRoute
  '/preferences': typeof PreferencesRoute
  '/shop': typeof ShopRoute
  '/taste': typeof TasteRoute
  '/welcome': typeof WelcomeRoute
  '/folders/$id': typeof FoldersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/board': typeof BoardRoute
  '/cart': typeof CartRoute
  '/inspo': typeof InspoRoute
  '/notifications': typeof NotificationsRoute
  '/preferences': typeof PreferencesRoute
  '/shop': typeof ShopRoute
  '/taste': typeof TasteRoute
  '/welcome': typeof WelcomeRoute
  '/folders/$id': typeof FoldersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/board': typeof BoardRoute
  '/cart': typeof CartRoute
  '/inspo': typeof InspoRoute
  '/notifications': typeof NotificationsRoute
  '/preferences': typeof PreferencesRoute
  '/shop': typeof ShopRoute
  '/taste': typeof TasteRoute
  '/welcome': typeof WelcomeRoute
  '/folders/$id': typeof FoldersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/board'
    | '/cart'
    | '/inspo'
    | '/notifications'
    | '/preferences'
    | '/shop'
    | '/taste'
    | '/welcome'
    | '/folders/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/board'
    | '/cart'
    | '/inspo'
    | '/notifications'
    | '/preferences'
    | '/shop'
    | '/taste'
    | '/welcome'
    | '/folders/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/board'
    | '/cart'
    | '/inspo'
    | '/notifications'
    | '/preferences'
    | '/shop'
    | '/taste'
    | '/welcome'
    | '/folders/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BoardRoute: typeof BoardRoute
  CartRoute: typeof CartRoute
  InspoRoute: typeof InspoRoute
  NotificationsRoute: typeof NotificationsRoute
  PreferencesRoute: typeof PreferencesRoute
  ShopRoute: typeof ShopRoute
  TasteRoute: typeof TasteRoute
  WelcomeRoute: typeof WelcomeRoute
  FoldersIdRoute: typeof FoldersIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspo': {
      id: '/inspo'
      path: '/inspo'
      fullPath: '/inspo'
      preLoaderRoute: typeof InspoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preferences': {
      id: '/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof PreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taste': {
      id: '/taste'
      path: '/taste'
      fullPath: '/taste'
      preLoaderRoute: typeof TasteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/folders/$id': {
      id: '/folders/$id'
      path: '/folders/$id'
      fullPath: '/folders/$id'
      preLoaderRoute: typeof FoldersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BoardRoute: BoardRoute,
  CartRoute: CartRoute,
  InspoRoute: InspoRoute,
  NotificationsRoute: NotificationsRoute,
  PreferencesRoute: PreferencesRoute,
  ShopRoute: ShopRoute,
  TasteRoute: TasteRoute,
  WelcomeRoute: WelcomeRoute,
  FoldersIdRoute: FoldersIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
